### ISSUE TITLE
has-binary

### ISSUE THREAD

**Issue by sujithktkm** [SoftwareEngineeringToolDemos/FSE-2011-EvoSuite#4]
No binary in repository. Only given as a link in README

**Comment by shabbirabdul** [comment]
@sujithktkm 
When you can download the binary from the official download page, why have binary committed to github when the no changes are not made to the original artifact?

**Comment by sujithktkm** [comment]
I mis-interpreted this issue. Will close it. Actually follow internal-binary issue, according to github repo creation guidelines, having binary as part of repo is required.

**Comment by shabbirabdul** [comment]
Thank you!
