### ISSUE TITLE
italics

### ISSUE THREAD

**Issue by sujithktkm** [SoftwareEngineeringToolDemos/FSE-2011-EvoSuite#5]
'is not' was not italicized in disclaimer.

**Comment by CaptainEmerson** [comment]
Use labels, please

**Comment by sujithktkm** [comment]
'italics' was the label given here 'In the disclaimer in the readme, does the project put "is not" in italics? [italics]' Professor. Please let me know if I did understand something wrong.

**Comment by CaptainEmerson** [comment]
https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by sujithktkm** [comment]
Professor, the owner of the repo did not give me owner permission yet, I assume that is the reason why I was not able to add labels for now. I will definitely update these once I get owner permissions. I was not aware I had to wait until getting owner permission before creating issues. I had some time to work on this assignment now and did so. Sorry if this was a mistake.

**Comment by shabbirabdul** [comment]
changed
